@Library('library') _
pipeline {
    agent any
    tools {
        maven "MAVEN"
    }

    stages {        
        stage('test') {
            steps {
               script {
                    mavenTest()
                }
            }
        }
        
        stage('Build') {
            steps {
               script {
                    mavenBuild()
                }
            }
        }

        stage('Deploy to Prod') {
            steps {
                script {
                    deploy()
                }
            }
        }
    }
}
