@Library('library') _
pipeline {
    agent any
    tools {
        maven "MAVEN"
    }

    stages {
        stage('checkout from SCM') {
            steps {
                script {
                    git()
                }
                
            }
        }
        
        stage('test') {
            steps {
               script {
                    mavenTest()
                }
            }
        }
        
        stage('Build') {
            steps {
               script {
                    mavenBuild()
                }
            }
        }
    }
}
