@Library('library') _
pipeline {
    agent any
    tools {
        maven "MAVEN"
    }

    stages {        
        stage('test') {
            steps {
               script {
                    mavenTest()
                }
            }
        }
        
        stage('Build') {
            steps {
               script {
                    mavenBuild()
                }
            }
        }

        stage('Deploy to Prod') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '160f6203-a1dc-4bdf-92c3-a9776e517949', path: '', url: 'http://192.168.1.9:8090')], contextPath: '/app', war: '**/*.war'
            }
        }
    }
}
